version: "3.3"

services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: bd_projeto
      POSTGRES_DB: bd_projeto_db
      TZ: "America/Sao_Paulo"
    ports:
      - 5436:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


